#pragma once

enum
{
    FRAME_ECHO_INPUT = 0,
    FRAME_ECHO_BACKWARD_FRAME_COUNT,
    FRAME_ECHO_FORWARD_FRAME_COUNT,
    FRAME_ECHO_BLEND_MODE,
    FRAME_ECHO_SYNC_FORWARD_BACKWARD,
    FRAME_ECHO_FORWARD_MAX_OPACITY,
    FRAME_ECHO_BACKWARD_MAX_OPACITY,
    FRAME_ECHO_FORWARD_WINDOW_FUNCTION,
    FRAME_ECHO_BACKWARD_WINDOW_FUNCTION,
    FRAME_ECHO_FORWARD_WINDOW_FALLOFF_RATIO,
    FRAME_ECHO_BACKWARD_WINDOW_FALLOFF_RATIO,
    FRAME_ECHO_FORWARD_WINDOW_FALLOFF_MAPPING,
    FRAME_ECHO_BACKWARD_WINDOW_FALLOFF_MAPPING,
    FRAME_ECHO_FRAME_SHORTAGE_BEHAVIOR,
    FRAME_ECHO_FRAME_SHORTAGE_COLOR,
    FRAME_ECHO_NUM_PARAMS,
};

enum
{
    FRAME_ECHO_BLEND_NEW_ON_TOP = 1,
    FRAME_ECHO_BLEND_NEW_ON_BOTTOM = 2,
    FRAME_ECHO_BLEND_ADD = 3,
    FRAME_ECHO_BLEND_MAXIMUM = 4,
    FRAME_ECHO_BLEND_MINIMUM = 5,
};

enum
{
    FRAME_ECHO_WINDOW_CONSTANT = 1,
    FRAME_ECHO_WINDOW_LINEAR = 2,
    FRAME_ECHO_WINDOW_SQUARE_ROOT = 3,
    FRAME_ECHO_WINDOW_SQUARE = 4,
    FRAME_ECHO_WINDOW_COSINE = 5,
    FRAME_ECHO_WINDOW_SMOOTH_STEP = 6,
};

enum
{
    FRAME_ECHO_WINDOW_FALLOFF_OUTPUT_MAPPED = 1,
    FRAME_ECHO_WINDOW_FALLOFF_INPUT_MAPPED = 2,
};

enum
{
    FRAME_ECHO_FRAME_SHORTAGE_BLANK_TRANSPARENT = 1,
    FRAME_ECHO_FRAME_SHORTAGE_REPEAT = 2,
    FRAME_ECHO_FRAME_SHORTAGE_SOLID_COLOR = 3,
};
